class ConfigJogo:

    TAM_TILE = 32
    ALTURA_MENU = 75
    LARGURA_TELA = TAM_TILE*20
    ALTURA_TELA = TAM_TILE*15 + ALTURA_MENU
    FONTE_SUBTITULO = 36
    COR_SUBTITULO = (255, 255, 255)
    COR_INICIO = (0, 0, 0)
    LARGURA_LOGO = LARGURA_TELA*.555
    ALTURA_LOGO = ALTURA_TELA*.453
    ESPACO_SUBTITULO = 1.3
    VELOCIDADE_PERSONAGEM = 1
    DURACAO_BOMBA = 2
    ALCANCE_BOMBA = 5
    MAX_BOMBA = 4
    DURACAO_JOGO = 120
    FONTE_HUD = 50
    COR_FONTE_HUD = (255, 255, 255)
