class ConfigJogo:
    TAM_TILE = 32
    LARGURA_TELA = TAM_TILE*20
    ALTURA_TELA = TAM_TILE*15
    FONTE_SUBTITULO = 36
    COR_SUBTITULO = (255, 255, 255)
    COR_INICIO = (0, 0, 0)
    LARGURA_LOGO = LARGURA_TELA*.555
    ALTURA_LOGO = ALTURA_TELA*.453
    ESPACO_SUBTITULO = 1.3
    VELOCIDADE_PERSONAGEM = 1
